root: true
env:
  node: true
extends: ["standard-with-typescript", "plugin:prettier/recommended"]
parser: "@typescript-eslint/parser"
parserOptions: 
  project: ["tsconfig.json", "src", "test"]
ignorePatterns: ["dist", "build", "node_modules"]
